export const KEYCLOACK_TOKEN = 'KEYCLOACK_TOKEN';
export const KEYCLOACK_MODULE_ID = 'KEYCLOACK_MODULE_ID';
export const KEYCLOACK_MODULE_OPTIONS = 'KEYCLOACK_MODULE_OPTIONS';

export const KEY_START = '-----BEGIN PUBLIC KEY-----';
export const KEY_END = '-----END PUBLIC KEY-----';
export const DEFAULT_ALGORITHMS = ['RS256'];
